name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  langchain: ^0.3.0
  langchain_openai: ^0.3.0
  pinecone: ^0.7.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
